
services:
  db:
    image: mariadb:10.3
    restart: always
    user: root
    volumes:
      - ./karera.sql:/docker-entrypoint-initdb.d/karera.sql
    environment:
      - MARIADB_DATABASE=zodiac
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
    ports:
      - 3306:3306
    expose:
      - 3306
    networks:
      - karera-network
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3


networks:
  karera-network: