import {
  ROLES,
  ROLES_REFERRALS_SELECT,
  TRANSACTION_STATUS_SELECT,
  TRANSACTION_TYPE_SELECT,
} from "../constants";

export const TRANSACTIONS_COLUMN = [
  {
    id: "trasactionId",
    numeric: false,
    disablePadding: false,
    label: "Transaction ID",
    filter: true,
  },
  {
    id: "callbackId",
    numeric: false,
    disablePadding: false,
    label: "Reference ID",
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Date",
    filter: true,
    filterType: "date",
    sort: true,
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    label: "Type",
    filterType: "select",
    filterTypeData: TRANSACTION_TYPE_SELECT,
    filter: true,
  },
  {
    id: "amount",
    numeric: false,
    disablePadding: false,
    label: "Amount",
    filter: true,
    sort: true,
  },
  {
    id: "status",
    numeric: false,
    disablePadding: false,
    label: "Status",
    filterType: "select",
    filterTypeData: TRANSACTION_STATUS_SELECT,
    filter: true,
  },
  {
    id: "playerName",
    numeric: false,
    disablePadding: false,
    label: "Player",
    filter: true,
    sort: true,
  },
  {
    id: "gameId",
    numeric: false,
    disablePadding: false,
    label: "Game ID",
    filter: true,
    sort: true,
  },
];

export const REFERRAL_COLUMN = [
  {
    id: "fullName",
    numeric: false,
    disablePadding: false,
    label: "Players",
    filter: true,
  },
  {
    id: "role",
    numeric: false,
    disablePadding: false,
    label: "Role",
    filter: true,
    filterType: "select",
    filterTypeData: ROLES_REFERRALS_SELECT,
  },
  {
    id: "mobile",
    numeric: false,
    disablePadding: false,
    label: "Mobile",
    filter: true,
  },
  {
    id: "commission",
    numeric: false,
    disablePadding: false,
    label: "Commission",
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created",
    filter: true,
    filterType: "date",
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "Updated",
    filter: true,
  },
];

export const NOTIFICATION_COLUMN = [
  {
    id: "isRead",
    numeric: false,
    disablePadding: false,
    label: "",
    filter: true,
  },
  {
    id: "message",
    numeric: false,
    disablePadding: false,
    label: "Message",
    filter: true,
  },
  {
    id: "module",
    numeric: false,
    disablePadding: false,
    label: "Module",
    filter: true,
  },
  {
    id: "type",
    numeric: false,
    disablePadding: false,
    label: "Type",
    filter: true,
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created",
    filter: true,
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "Updated",
    filter: true,
  },
];

export const LOGS_COLUMN = [
  {
    id: "functionality",
    numeric: false,
    disablePadding: false,
    label: "Functionality",
    filter: true,
  },
  {
    id: "message",
    numeric: false,
    disablePadding: false,
    label: "Message",
    filter: true,
  },
  {
    id: "level",
    numeric: false,
    disablePadding: false,
    label: "Level",
    filter: true,
  },
  {
    id: "associatedId",
    numeric: false,
    disablePadding: false,
    label: "Associated ID",
    filter: true,
  },
  {
    id: "associatedType",
    numeric: false,
    disablePadding: false,
    label: "Associated Type",
    filter: true,
  },
   {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created Date",
    filter: true,
    filterType: "date",
  },
];

export const USER_MANAGEMENT_COLUMN = [
  { id: "profilePicture", numeric: false, disablePadding: false, label: "" },
  {
    id: "name",
    numeric: false,
    disablePadding: false,
    label: "Name",
    filter: true,
  },
  {
    id: "mobile",
    numeric: false,
    disablePadding: false,
    label: "Mobile",
    filter: true,
  },
  {
    id: "role",
    numeric: false,
    disablePadding: false,
    label: "Roles",
    filter: true,
    role: [],
  },
  {
    id: "status",
    numeric: false,
    disablePadding: false,
    label: "Status",
    role: [
      ROLES.ADMINISTRATOR.name, 
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
    ],
    filter: true,
  },
  {
    id: "supervisor",
    numeric: false,
    disablePadding: false,
    label: "Supervisor",
    // the role that list here is cannot view this column
    role: [
      ROLES.SUPERVISOR.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
    ],
    filter: true,
  },
  {
    id: "verifier",
    numeric: false,
    disablePadding: false,
    label: "Verifier",
    // the role that list here is cannot view this column
    role: [
      ROLES.VERIFIER.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
    ],
    filter: true,
  },
  {
    id: "verifierApprovedAt",
    numeric: false,
    disablePadding: false,
    label: "Action Date",
    role: [
      ROLES.VERIFIER.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
    ],
  },
  {
    id: "supervisorApprovedAt",
    numeric: false,
    disablePadding: false,
    label: "Action Date",
    role: [
      ROLES.SUPERVISOR.name,
      ROLES.ADMINISTRATOR.name,
      ROLES.SUPERADMIN.name,
      ROLES.OPERATOR.name,
      ROLES.MASTERAGENT.name,
    ],
  },
  {
    id: "createdAt",
    numeric: false,
    disablePadding: false,
    label: "Created",
    filter: true,
    filterType: "date",
  },
  {
    id: "updatedAt",
    numeric: false,
    disablePadding: false,
    label: "Updated",
    filter: true,
    filterType: "date",
  },
  { id: "actions", numeric: false, disablePadding: false, label: "" },
];
